irclog/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'irclog'
admin.AdminSite.site_header = app_name + ' Administration'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('api/v1/post', views.api_v1_post, name='api_v1_post'),
    path('api/v1/search', views.api_v1_search, name='api_v1_search'),
    path('api/v1/next', views.api_v1_next, name='api_v1_next'),
    path('api/v1/now', views.api_v1_now, name='api_v1_now'),
    path('api/v1/previous', views.api_v1_previous, name='api_v1_previous'),
    path('api/v1/allchannels', views.api_v1_allchannels, name='api_v1_allchannels'),
]

maobot/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('irclog/', include('irclog.urls')),
    path('ircimages/', include('ircimages.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

irclog/models.py
from django.db import models
from django.utils import timezone

# Create your models here.


class Channel(models.Model):
    name = models.CharField('channel name', max_length=50, unique=True)
    topic = models.TextField('channel topic', null=True)
    ircusers = models.CharField('channel user', max_length=100, null=True)

    def __str__(self):
         return self.name


class Log(models.Model):
    AVAILABLE_COMMAND = (
        ('PRIVMSG', 'priv'),
        ('NOTICE', 'notice'),
    )
    command = models.CharField('irc command', max_length=10,
                               choices=AVAILABLE_COMMAND,
                               default='PRIVMSG')
    channel = models.ForeignKey(
        'Channel', null=True, on_delete=models.SET_NULL, default=1)
    nick = models.CharField('irc nick', max_length=20, default="test")
    message = models.CharField('irc message', max_length=500)
    attached_image = models.ImageField(
        'attached image', null=True, blank=True)
    created_at = models.DateTimeField('date created', default=timezone.now)
    is_irc = models.BooleanField(default=True)
    is_from_log = models.BooleanField(default=False)

    class Meta:
        ordering = ['-id']

    def __str__(self):
        return '%s [%s] %s: %s' % (
                self.created_at.strftime('%Y-%m-%d %H:%M:%S'), 
                self.channel, self.nick, self.message)

irclog/forms.py
import datetime
import os
import subprocess
import uuid

from django import forms
from django.core.files import File
from django.utils import timezone

from ircimages.models import Image
from .models import Log

DEFAULT_START_AT = timezone.now() - datetime.timedelta(hours=3)
DEFAULT_END_AT = timezone.now()
INPUT_FORMATS = ['%Y-%m-%dT%H:%M:%S']


class LogCreateForm(forms.ModelForm):
    """Form to create log with image."""

    class Meta:
        model = Log
        fields = ('channel', 'nick', 'command', 'message', 'attached_image')

    def save(self, commit=True):
        instance = super().save(commit=False)
        instance.is_irc = False
        instance.is_from_log = True

        # handle attached image
        img_temp = self.cleaned_data.get('attached_image')
        if img_temp:
            image = Image(related_log=instance)
            image.image.save(str(uuid.uuid4()).replace('-', ''), File(img_temp))
            instance.attached_image = image.thumb
        if commit:
            instance.save()
        return instance

irclog/views.py
import datetime
from datetime import datetime as dt
import re

from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import JsonResponse
from django.utils import timezone
from django.views.generic import CreateView

from .forms import LogCreateForm
from .models import Channel, Log


# Create your views here.
class IndexView(LoginRequiredMixin, CreateView):
    """
    path: /irclog/
    Just an index.
    """
    template_name = 'irclog/index.html'
    model = Log
    form_class = LogCreateForm

    login_url = 'accounts:login'
    redirect_field_name = 'redirect_to'

    def get_context_data(self, **kwargs):
        # Make context
        context = super(IndexView, self).get_context_data(**kwargs)
        context['current_user'] = self.request.user
        return context


def api_v1_allchannels(request):
    """
    Returns joined channel lists.
    """
    channels = Channel.objects.all()
    channel_list = []
    for c in channels:
        channel = {'id': c.id,
                   'name': c.name,
                   'members': c.ircusers,
                   'topic': c.topic,}
        channel_list.append(channel)
    return JsonResponse({'channels': channel_list})


def get_irclog_info(start_at, end_at, keyword=''):
    """
    Returns irclog information.
    :param start_at: find log from the time
    :param end_at: find log till the time
    :param keyword: find log with the keyword
    :return: a dict including a log list
    """
    results = Log.objects.filter(created_at__range=(start_at, end_at + datetime.timedelta(minutes=1))
                                 ).filter(message__contains=keyword).order_by('created_at')
    log_list = []
    for result in results:
        url_pat = r"https?://[a-zA-Z0-9\-./?@&=:~_#]+"
        message = result.message
        match_url = re.search(url_pat, message)
        if match_url:
            find = re.finditer(url_pat, message)
            for f in find:
                url = message[f.start():f.end()]
                message = message[:f.start()] + '<a href="' + url + '">' + url + '</a>' + message[f.end():]
        log = {'created_at': result.created_at.strftime('%Y-%m-%d %H:%M:%S'),
               'command': result.command,
               'message': message,
               'channel': result.channel.id,
               'nick': result.nick,
               'is_from_log': result.is_from_log,
               }
        if result.attached_image:
            log['attached_image_url'] = result.attached_image.url
        log_list.append(log)
    irclog_info = {
        'log_list': log_list,
        'start_at': start_at.strftime('%Y-%m-%dT%H:%M'),
        'end_at': end_at.strftime('%Y-%m-%dT%H:%M'),
        'channel_id_list': [c.id for c in Channel.objects.all()]
    }
    return irclog_info


# CreateLogForm
def api_v1_post(request):
    """
    API to post a log
    :param request:
    :return:
    """
    if request.is_ajax() and request.method == 'POST':
        create_form = LogCreateForm(request.POST)
        if create_form.is_valid():
            create_form.save()
            return JsonResponse({'created_at': timezone.now().strftime('%Y-%m-%d %H:%M:%S'),
                                 'end_at': timezone.now().strftime('%Y-%m-%dT%H:%M'),
                                 'message': create_form.cleaned_data.get('message'),
                                 'channel': create_form.cleaned_data.get('channel').id})


# SearchLogForm
def api_v1_search(request):
    """
    API when pressing search
    :param request:
    :return:
    """
    if request.is_ajax() and request.method == 'GET':
        start_at = dt.strptime(request.GET['start_at'], '%Y-%m-%dT%H:%M')
        end_at = dt.strptime(request.GET['end_at'], '%Y-%m-%dT%H:%M')
        keyword = request.GET['keyword']

        irclog_info = get_irclog_info(start_at, end_at, keyword)
        return JsonResponse(irclog_info)


def api_v1_now(request):
    """
    API when pressing now
    :param request:
    :return: log list
    """
    if request.is_ajax() and request.method == 'GET':
        start_at = timezone.now() - datetime.timedelta(hours=3)
        end_at = timezone.now()

        irclog_info = get_irclog_info(start_at, end_at)
        return JsonResponse(irclog_info)


def api_v1_next(request):
    if request.is_ajax() and request.method == 'GET':
        start_at = dt.strptime(request.GET['start_at'], '%Y-%m-%dT%H:%M')
        end_at = dt.strptime(request.GET['end_at'], '%Y-%m-%dT%H:%M')

        duration = end_at - start_at
        end_at += duration
        start_at += duration

        irclog_info = get_irclog_info(start_at, end_at)
        return JsonResponse(irclog_info)


def api_v1_previous(request):
    if request.is_ajax() and request.method == 'GET':
        start_at = dt.strptime(request.GET['start_at'], '%Y-%m-%dT%H:%M')
        end_at = dt.strptime(request.GET['end_at'], '%Y-%m-%dT%H:%M')

        duration = end_at - start_at
        end_at -= duration
        start_at -= duration

        irclog_info = get_irclog_info(start_at, end_at)
        return JsonResponse(irclog_info)

irclog/templates/irclog/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block extrahead %}
<link rel="stylesheet" href="{% static 'irclog/css/irc.css' %}">
{% endblock %}
{% block content %}
<div class="container-fluid" style="margin-bottom: 30px;">
    <div class="row">
        <nav class="col-2 d-none d-md-block bg-light sidebar nav nav-pills">
            <div class="list-group" id="channelList" role="tablist"></div>
            <button id="image_button" onclick="imageButton()" type="button" class="btn btn-primary" data-toggle="button" aria-pressed="false" autocomplete="off">
                image
            </button>
        </nav>
        <main role="main" class="col-10 ml-sm-auto col-lg-10 pt-3">
            <div class="tab-content" id="log-list"></div>

            <!-- LogCreateForm -->
            <div id="create-form" class="row">
                {% csrf_token %}
                <input type="hidden" value="{{ current_user.username }}" id="nick" name="nick"/>
                <input type="hidden" value="1" id="current_channel_id" name="channel"/>

                <label class="sr-only" for="command">command</label>
                <select class="col-1 form-control" name="command" required id="command">
                    <option value="PRIVMSG" selected>privmsg</option>
                    <option value="NOTICE">notice</option>
                </select>

                <label class="sr-only" for="message">message</label>
                <input type="text" class="col-10 form-control" name="message" required id="message" placeholder="Message" />
                <label for="attached_image" class="sr-only">attached_image</label>
                <!--input type="file" class="col-2" name="attached_image" id="attached_image"-->
                <button onclick="submitCreateForm()" class="col-1 btn btn-primary">送信</button>
            </div>
        </main>
    </div>
</div>
            <!-- SearchLogForm -->
<nav class="navbar fixed-bottom navbar-light bg-light navbar-expand-lg row">
    <label class="sr-only" for="keyword">keyword</label>
    <input type="text" class="form-control col-2" name="keyword" id="keyword" placeholder="keyword" value="" />
    <input type="datetime-local" class="form-control col-3" name="start_at" required id="start_at" value="" />
    <input type="datetime-local" class="form-control col-3" name="end_at" required id="end_at" value="" />
    <button id="search" onclick="submitSearchForm('{% url "irclog:api_v1_search" %}')" class="btn btn-light col-1">search</button>
    <button id="previous" onclick="submitSearchForm('{% url "irclog:api_v1_previous" %}')" class="btn btn-light col-1" name="previous_duration">&lt;&lt;</button>
    <button id="now" onclick="submitSearchForm('{% url "irclog:api_v1_now" %}')" class="btn btn-light col-1" name="now">○</button>
    <button id="next" onclick="submitSearchForm('{% url "irclog:api_v1_next" %}')" class="btn btn-light col-1" name="next_duration">&gt;&gt;</button>
</nav>
{% endblock content %}
{% block extrabody %}
    <script src="https://cdn.jsdelivr.net/npm/js-cookie@2/src/js.cookie.min.js"></script>
    <script>
        shown_image = false;

        $('#message').keypress(function(e) {
            if (e.which == 13) {
                submitCreateForm();
                return false;
            }
        });
        $('#channelList').on('click', 'a.nav-link', function (_) {
            $('#current_channel_id').val($(this).attr('val'));
        });
        function csrfSafeMethod(method) {
        // these HTTP methods do not require CSRF protection
            return (/^(GET|HEAD|OPTIONS|TRACE)$/.test(method));
        }
        var csrftoken = Cookies.get('csrftoken');
        $.ajaxSetup({
            beforeSend: function(xhr, settings) {
                if (!csrfSafeMethod(settings.type) && !this.crossDomain) {
                    xhr.setRequestHeader("X-CSRFToken", csrftoken);
                }
            }
        });
        function submitSearchForm(url) {
            $('#message').val('');
            $.ajax({
                url: url,
                type: 'GET',
                data: {
                    'start_at': $('#start_at').val(),
                    'end_at': $('#end_at').val(),
                    'keyword': $('#keyword').val()
                },
                dataType: 'json',
                success: function(response){
                    $('#start_at').val(response.start_at);
                    $('#end_at').val(response.end_at);
                    $.each(response.channel_id_list, function(_, channel_id) {
                        var log_list = $("#channel_id_" + channel_id + "_body");
                        log_list.html('');
                        $.each(response.log_list, function(index, log) {
                            if (log.channel == channel_id) {
                                log_list.append('<tr class="row no-gutters" id="tr' + index + '"></tr>');
                                var tr = $("#tr" + index);
                                tr.append('<td class="irc time">' + log.created_at + '</td>');
                                if (log.is_from_log) {
                                    tr.append('<td class="irc name"> [' + log.nick + ']</td>');
                                } else {
                                    tr.append('<td class="irc name"> (' + log.nick + ')</td>');
                                }
                                if (log.command === "PRIVMSG") {
                                    tr.append('<td class="irc priv"> ' + log.message + '</td>');
                                } else {
                                    tr.append('<td class="irc noti"> ' + log.message + '</td>');
                                }
                                if (log.attached_image_url) {
                                    if (shown_image) {
                                            log_list.append('<tr class="attached_image row no-gutters"><td><img src="{{ MEDIA_URL }}' + log.attached_image_url + '" /></td></tr>');
                                    } else {
                                            log_list.append('<tr class="attached_image row no-gutters" style="display: none"><td><img src="{{ MEDIA_URL }}' + log.attached_image_url + '" /></td></tr>');
                                    }
                                }
                            }
                        })
                    })
                }
            });
            return false;
        }
        function submitCreateForm() {
            var formData = new FormData();
            //formData.append('attached_image', $('#attached_image')[0].files[0]);
            formData.append('nick', $('#nick').val());
            formData.append('command', $('#command').val());
            formData.append('message', $('#message').val());
            formData.append('channel', $('#current_channel_id').val());
            $.ajax({
                url: '{% url "irclog:api_v1_post" %}',
                type: 'POST',
                data: formData,
                //dataType: 'json',
                contentType: false,
                processData: false,
                cache: false,
                success: function(response) {
                    submitSearchForm('{% url "irclog:api_v1_now" %}')
                }
            });
            $('#create-form')[0].scrollIntoView(true);
            return false;
        }
        function imageButton() {
            if ($('#image_button').attr('aria-pressed') === 'false') {
               shown_image = true;
               $(".attached_image").show();
            } else {
               shown_image = false;
               $(".attached_image").hide();
            }
        }
        $().ready(function () {
            $.ajax({
                url: '{% url "irclog:api_v1_allchannels" %}',
                type: 'POST',
                contentType: false,
                processData: false,
                cache: false,
                success: function(response) {
                    $.each(response.channels, function(i, c){
                        if (c.id == '1') {
                            $('#channelList').append("<a class='list-group-item list-group-item-action nav-link active' id='channel_id_" + c.id +"-tab' data-toggle='list' href='#channel_id_" + c.id + "' role='tab' val=" + c.id + ">" + c.name + "<br />" + c.members + "<br />" + c.topic + "</a>");
                            $('#log-list').append("<div class='tab-pane active' id='channel_id_" + c.id + "' role='tabpanel' aria-labelledby='channel_id_" + c.id + "-tab'><div class='table-responsive'><table class='table table-striped table-sm'><tbody id='channel_id_" + c.id + "_body'></tbody></table></div></div>");
                        } else {
                            $('#channelList').append("<a class='list-group-item list-group-item-action nav-link' id='channel_id_" + c.id +"-tab' data-toggle='list' href='#channel_id_" + c.id + "' role='tab' val=" + c.id + ">" + c.name + "<br />" + c.members + "<br />" + c.topic + "</a>");
                            $('#log-list').append("<div class='tab-pane' id='channel_id_" + c.id + "' role='tabpanel' aria-labelledby='channel_id_" + c.id + "-tab'><div class='table-responsive'><table class='table table-striped table-sm'><tbody id='channel_id_" + c.id + "_body'></tbody></table></div></div>");}
                    })
                }

            });
            submitSearchForm('{% url "irclog:api_v1_now" %}');
        });
    </script>
{% endblock %}