accounts/urls.py
from django.contrib import admin
from django.urls import path
from django.contrib.auth import views as auth_views

from . import views

app_name = 'accounts'
admin.AdminSite.site_header = app_name + ' Administration'
urlpatterns = [
    path('', views.index, name='index'),
    path('login/', auth_views.LoginView.as_view(
         template_name='accounts/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(
         template_name='accounts/logout.html'), name='logout'),
    path('new/', views.new, name='new'),
    path('create/', views.create, name='create'),
]

irclog/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'irclog'
admin.AdminSite.site_header = app_name + ' Administration'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('api/v1/post', views.api_v1_post, name='api_v1_post'),
    path('api/v1/search', views.api_v1_search, name='api_v1_search'),
    path('api/v1/next', views.api_v1_next, name='api_v1_next'),
    path('api/v1/now', views.api_v1_now, name='api_v1_now'),
    path('api/v1/previous', views.api_v1_previous, name='api_v1_previous'),
    path('api/v1/allchannels', views.api_v1_allchannels, name='api_v1_allchannels'),
]

maobot/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('irclog/', include('irclog.urls')),
    path('ircimages/', include('ircimages.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

accounts/models.py
from django.contrib.auth.models import AbstractUser
from django.db import models


# Create your models here.
class IrcUser(AbstractUser):
    email = models.EmailField('Email Address', blank=True, null=True)

accounts/forms.py
from django.contrib.auth.forms import UserCreationForm
from django import forms

from .models import IrcUser


class IrcUserCreationForm(UserCreationForm):

    passphrase = forms.CharField(max_length=10)

    class Meta:
        model = IrcUser
        fields = (
            'username', 'password1', 'password2', 'passphrase')

    def clean(self):
        cleaned_data = super(IrcUserCreationForm, self).clean()

        if cleaned_data.get('passphrase') != 'naokun':
            self.add_error('passphrase', 'Wrong passphrase')

accounts/views.py
from django.contrib.auth.decorators import login_required
from django.http import Http404, HttpResponseRedirect
from django.shortcuts import render, redirect

from .forms import IrcUserCreationForm


# Create your views here.
@login_required
def index(request):
    return render(request, 'accounts/index.html')


def new(request):
    form = IrcUserCreationForm()
    return render(request, 'accounts/new.html', {'form': form, })


def create(request):
    if request.method == 'POST':
        form = IrcUserCreationForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('irclog:index')
        return render(request, 'accounts/new.html', {'form': form,})
    else:
        raise Http404

accounts/templates/accounts/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>Title</title>
</head>
<body>

</body>
</html>

accounts/templates/accounts/login.html
{% block content %}

{% if form.errors %}
<p>Your username and password didn't match. Please try again.</p>
{% endif %}

{% if next %}
    {% if user.is_authenticated %}
        <p>Your account doesn't have access to this page. To proceed,
            please login with an account that has access.</p>
    {% else %}
        <p>Please login to see this page.</p>
    {% endif %}
{% endif %}

<form method="post" action="{% url 'accounts:login' %}">
{% csrf_token %}
<table>
  <tr>
    <td>{{ form.username.label_tag }}</td>
    <td>{{ form.username }}</td>
  </tr>
  <tr>
    <td>{{ form.password.label_tag }}</td>
    <td>{{ form.password }}</td>
  </tr>
</table>

<input type="submit" value="login" />
<input type="hidden" name="next" value="" />
</form>

<p><a href="{% url 'accounts:new' %}">NEW ACCOUNT</a></p>

{# Assumes you setup the password_reset view in your URLconf #}
{# <p><a href="{% url 'password_reset' %}">Lost password?</a></p> #}

{% endblock %}

accounts/templates/accounts/logout.html
{% block title %}ログアウト{% endblock title %}

{% block content %}

    <h3 class="page-header">ログアウトしました</h3>

{% endblock content %}

accounts/templates/accounts/new.html
{% extends "base.html" %}
{% load staticfiles %}
{% block extrahead %}
<link href="{% static 'accounts/css/regist.css' %}" rel="stylesheet">
{% endblock %}
{% block content %}
<div class="container">
<form method="POST" action="{% url 'accounts:create' %}">
    {% csrf_token %}
    <div class="form-signin">
    <h2 class="form-signin-heading">ユーザー登録</h2>
    <h3>passphraseはheiqi鯖の元共通パス</h3>
    {{ form.non_field_errors }}
    <label for="{{ form.username.id_for_label }}" class="sr-only">ユーザー名</label>
    <input type="text" id="{{ form.username.id_for_label }}" name="{{ form.username.name }}" class="form-control" placeholder="ユーザー名" required autofocus />

    {{ form.errors.password1 }}
    <label for="{{ form.password1.id_for_label }}" class="sr-only">パスワード</label>
    <input type="password" id="{{ form.password1.id_for_label }}" name="{{ form.password1.name }}"class="form-control" placeholder="パスワード" required />

    {{ form.errors.password2 }}
    <label for="{{ form.password2.id_for_label }}" class="sr-only">パスワード確認</label>
    <input type="password" id="{{ form.password2.id_for_label }}" name="{{ form.password2.name }}"class="form-control" placeholder="パスワード（確認）" required />

    {{ form.errors.passphrase }}
    <label for="{{ form.passphrase.id_for_label }}" class="sr-only">パスフレーズ</label>
    <input type="text" id="{{ form.passphrase.id_for_label }}" name="{{ form.passphrase.name }}" class="form-control" placeholder="パスフレーズ" required />
    <br />
    <button class="btn btn-lg btn-primary btn-block" type="submit" value="Create" />ユーザー登録</button>
    </div>
</form>
</div>
{% endblock %}