ircimages/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'ircimages'
admin.AdminSite.site_header = app_name + ' Administration'
urlpatterns = [
    path('', views.ImageListView.as_view(), name='index'),
]

irclog/urls.py
from django.contrib import admin
from django.urls import path

from . import views

app_name = 'irclog'
admin.AdminSite.site_header = app_name + ' Administration'
urlpatterns = [
    path('', views.IndexView.as_view(), name='index'),
    path('api/v1/post', views.api_v1_post, name='api_v1_post'),
    path('api/v1/search', views.api_v1_search, name='api_v1_search'),
    path('api/v1/next', views.api_v1_next, name='api_v1_next'),
    path('api/v1/now', views.api_v1_now, name='api_v1_now'),
    path('api/v1/previous', views.api_v1_previous, name='api_v1_previous'),
    path('api/v1/allchannels', views.api_v1_allchannels, name='api_v1_allchannels'),
]

maobot/urls.py
from django.conf import settings
from django.conf.urls.static import static
from django.contrib import admin
from django.urls import include, path
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='index.html')),
    path('irclog/', include('irclog.urls')),
    path('ircimages/', include('ircimages.urls')),
    path('accounts/', include('accounts.urls')),
    path('admin/', admin.site.urls),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

templates/base.html
{% load staticfiles %}
{% load irc_exists %}
<!DOCTYPE html>
<html lang="{{ LANGUAGE_CODE|default:"ja" }}">
<head>
<meta charset="UTF-8">
<title>{% block title %}maobot{% endblock %}</title>
<meta name="viewport" content="width=device-width, initial-scale=1.0">
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/css/bootstrap.min.css" integrity="sha384-WskhaSGFgHYWDcbwN70/dfYBj47jz9qbsMId/iRN3ewGhXQFZCSftd1LZCfmhktB" crossorigin="anonymous">
<link rel="stylesheet" href="{% static 'css/grid.css' %}">
<!--link rel="stylesheet" href="https://v4-alpha.getbootstrap.com/dist/css/bootstrap.min.css"-->
{% block extrahead %}{% endblock %}
</head>
<body>
<nav class="navbar navbar-expand-md navbar-dark bg-dark fixed-top">
  <a class="navbar-brand" href="../">maobot</a>
  <button type="button" class="navbar-toggler" data-toggle="collapse" data-target="#Navbar" aria-controls="Navbar" aria-expanded="false" aria-label="label">
    <span class="navbar-toggler-icon"></span>
  </button>
  <div class="collapse navbar-collapse" id="Navbar">
    <ul class="navbar-nav mr-auto">
      <li class="nav-item"><a class="nav-link" href="{% url 'irclog:index' %}">irclog</a></li>
      <li class="nav-item"><a class="nav-link" href="{% url 'ircimages:index' %}">ircimages</a></li>
      <li class="nav-item"><a class="nav-link" href="http://www.vert-utopia.com/mypage/maobot_php/irclog.php">旧irclog</a></li>
      <li class="nav-item"><a class="nav-link" href="#">ircvideos</a></li>
      <li class="nav-item"><a class="nav-link" href="http://www.vert-utopia.com/mypage/wiki/">wiki</a></li>
      <li class="nav-item"><a class="nav-link" href="http://www.vert-utopia.com/blog/">blog</a></li>
    </ul>
    {% if 'ircon'|irc_exists %}
    <div style="font-size:1em; color:green">
    {% else %}
    <div style="font-size:1em; color:red">
    {% endif %}
       <i class="fas fa-circle"></i>
    </div>
    <span class="navbar-text">
       {{ request.user }}
    </span>
  </div>
</nav>
      {% block content %}
      {{ content }}
      {% endblock %}
  <script src="https://code.jquery.com/jquery-3.3.1.min.js" integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=" crossorigin="anonymous"></script>
  <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.3/umd/popper.min.js" integrity="sha384-ZMP7rVo3mIykV+2+9J3UJ46jBk0WLaUAdn689aCwoqbBJiSnjAK/l8WvCWPIPm49" crossorigin="anonymous"></script>
  <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.1.1/js/bootstrap.min.js" integrity="sha384-smHYKdLADwkXOn1EmN1qk/HfnUcbVRZyYmZ4qpPea6sjB/pTJ0euyQp0Mk8ck+5T" crossorigin="anonymous"></script>
  <script defer src="https://use.fontawesome.com/releases/v5.0.4/js/all.js"></script>
  {% block extrabody %}{% endblock %}
</body>
</html>

templates/index.html
{% extends "base.html" %}
{% load staticfiles %}
{% block content %}
<h1>MAOBOT</h1>
{% endblock %}